version: '3.8'
services:
  traefik:
    image: traefik:2.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - traefik

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    ports:
      - "8888:80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.entrypoints=whoami"
      - "traefik.http.routers.whoami.rule=Host(`tchit-cloud.ddns.net`)"
    networks:
      - traefik

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    hostname: tchit-cloud.ddns.net
    environment:
      - TZ='Europe/Paris'
      - PLEX_CLAIM='claim-s6zRn4iAb_zB7LE6M9mp'
      - ADVERTISE_IP=https://tchit-cloud.ddns.net
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - /media/info/DATAS:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.rule=Host(`tchit-cloud.ddns.net`)"
    networks:
      - traefik

volumes:
  plex_config:
    name: plex_config

  plex_transcode:
    name: plex_transcode

networks:
  traefik:
    name: traefik
